GET http://127.0.0.1:8000/api/v1/posts/

###

POST http://127.0.0.1:8000/api/v1/users/
Content-Type: application/json

{
    "username": "admin_1",
    "password": "admin_strong"
}

###

POST http://127.0.0.1:8000/api/v1/users/
Content-Type: application/json

{
    "username": "admin_2",
    "password": "admin_2_strong"
}

###

POST http://127.0.0.1:8000/api/v1/jwt/create/
Content-Type: application/json

{
    "username": "admin_1",
    "password": "admin_strong"
}

###

POST http://127.0.0.1:8000/api/v1/jwt/verify/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MjA1NTAzLCJpYXQiOjE3NDQxMTkxMDMsImp0aSI6IjJmZDU2ZmVkYWZmMzQ1M2U4MjNkOTkyZThiNzZiMDBkIiwidXNlcl9pZCI6MX0.nPm3vNWdN_Q5qzAKn66oTPuVAC7zZ-_uHp-ZPG82J7U"
}

###

POST http://127.0.0.1:8000/api/v1/jwt/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NDIwNTc2NiwiaWF0IjoxNzQ0MTE5MzY2LCJqdGkiOiI4MDA0MWU2YTNiOTc0MmQyYTRiNGU5NmIxNmU2MGE4ZiIsInVzZXJfaWQiOjF9.k_FoT63Vna3gFtL77_qvkfyjI5qGZRc1FeVyeTCtIXY"
}

###

GET http://127.0.0.1:8000/api/v1/posts/

###

POST http://127.0.0.1:8000/api/v1/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MjExNzU2LCJpYXQiOjE3NDQxMjUzNTYsImp0aSI6ImFhMTY3M2IzODAwODQyYWU5YzNmMTBiYzg4MmI2MTNjIiwidXNlcl9pZCI6MX0.dTz9juMuZhODEMx1Uf8XAIvxMcXf-q9M2vLz_TsLZgY
Content-Type: application/json


{
  "text": "Post 1",
  "image": null,
  "group": null
}

###

GET http://127.0.0.1:8000/api/v1/groups/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MjExNzU2LCJpYXQiOjE3NDQxMjUzNTYsImp0aSI6ImFhMTY3M2IzODAwODQyYWU5YzNmMTBiYzg4MmI2MTNjIiwidXNlcl9pZCI6MX0.dTz9juMuZhODEMx1Uf8XAIvxMcXf-q9M2vLz_TsLZgY
Content-Type: application/json

### 

GET http://127.0.0.1:8000/api/v1/follow/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MjExNzU2LCJpYXQiOjE3NDQxMjUzNTYsImp0aSI6ImFhMTY3M2IzODAwODQyYWU5YzNmMTBiYzg4MmI2MTNjIiwidXNlcl9pZCI6MX0.dTz9juMuZhODEMx1Uf8XAIvxMcXf-q9M2vLz_TsLZgY
Content-Type: application/json

### 

POST http://127.0.0.1:8000/api/v1/follow/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MjExNzU2LCJpYXQiOjE3NDQxMjUzNTYsImp0aSI6ImFhMTY3M2IzODAwODQyYWU5YzNmMTBiYzg4MmI2MTNjIiwidXNlcl9pZCI6MX0.dTz9juMuZhODEMx1Uf8XAIvxMcXf-q9M2vLz_TsLZgY
Content-Type: application/json

{
    "following": "admin_2"
}